---
  title: "Reference Materials"
---
  
These materials / links were last checked on October 2, 2025. All apologies for links that no longer work. Please email me at [CRunyon@nbme.org](mailto:CRunyon@nbme.org) if you notice something no longer works so I can change / remove the link.
  
## Background Information on GPTs

The [3Blue1Brown YouTube Channel](https://www.youtube.com/c/3blue1brown) provides several good videos on the some of the technical aspects of large language models.

* The [Neural Networks](https://www.youtube.com/playlist?list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi) section is particularly informative.

Anthropic's paper [On the Biology of a Large Language Model](https://transformer-circuits.pub/2025/attribution-graphs/biology.html) is particularly interesting.

This [post on lesswrong](https://www.lesswrong.com/posts/XGHf7EY3CK4KorBpw/understanding-llms-insights-from-mechanistic) provides a nice high-level summary for understanding LLMs.

## Reference Guides (and Prompt Engineering)

[OpenAI Cookbook](https://cookbook.openai.com/)

## Shiny-related Resources

Posit has [many useful things](https://shiny.posit.co/).

- [Materials for the R language start here](https://shiny.posit.co/r/getstarted/shiny-basics/lesson1/).
- [Materials for the Python language start here](https://shiny.posit.co/py/).

[nanxstats has nicely organized many Shiny extension packages.](https://github.com/nanxstats/awesome-shiny-extensions)

## Legal Considerations

The information provided here is for general informational purposes only and does not constitute legal advice. You should not act upon any information presented without first seeking qualified legal counsel regarding your specific situation. The authors disclaim any liability for actions taken based on the content provided here.
