project:
  type: book
  output-dir: _book

book:
  title: "Integrating Generative AI into R Workflows: From APIs to Shiny Apps"
  author: "Christopher Runyon"
  date: last-modified

  page-footer:
    left: |
      Copyright © `r format(Sys.Date(), "%Y")` by Christopher Runyon.<br> 
      Licensed under [CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/)
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  
  cover-image: SimpleBookCover_Image.png
  favicon: therefore.png
  
  chapters:
    - index.qmd
    
    - part: "Setup"
      chapters: 
        - 01-R-setup.qmd
        - 02-R-packages.qmd
        - 03-test-connect.qmd
        - 04-api-implementation.qmd
        - 05-api-keys.qmd
         
    - part: "GenAI Models Overview"
      chapters: 
        - 06-gen-ai-fundamentals.qmd
        - 07-gen-ai-basics.qmd
        - 08-gen-ai-parameters.qmd
        - 09-activity-temp-tester.qmd #09
        # Activity: Parameter Testing App

    - part: "LLM Workflows with R"
      chapters: 
        - 10-sample-workflow.qmd #10
        - 11-practical-tools.qmd #11
        - 12-integration.qmd #12
        - 13-conversations-via-api.qmd #13
        - 14-activity-conversations-via-api.qmd #14
        # Activity: `ellmer`
        - 15-single-interactions-via-api.qmd #15
        - 16-activity-iterative-prompt-development.qmd #16
        # Activity: Prompt development & refinement
        - 17-batch-processing.qmd #17
        - 18-activity-batch-processing.qmd #18
        # Activity: Batch processing
        - 19-mitigating-variability.qmd #19
        - 20-chained-workflows.qmd #20
        - 21-activity-prompt-chaining.qmd #21
        # Activity: Simple chained workflows
        - 22-calling-other-llms.qmd #22

    - part: "Vibe Coding with Shiny"
      chapters: 
        - 23-shiny.qmd #23
        - 24-vibe-coding.qmd #24
        - 25-shiny-integration.qmd #25
        - 26-activity-make-llm-shiny-app.qmd #26
        # Activity: Make Shiny App with LLM Call
        - 27-saving-shiny-data.qmd #27

    - part: "Resources"
      chapters: 
        - 28-reference-materials.qmd #28
        - 29-acknowledgements.qmd #29
        - 30-references.qmd #30
        
    # - part: "Retired Pages"
    #   chapters: 
    #     - ret-intro.qmd
    #     - activity-parameter-testing.qmd
    #     - 14-prompt-engineering.qmd
    #     - 15-prompt-formulas.qmd
    #     - activity-prompt-engineering.qmd
    #     - activity-chained-workflows.qmd
    #     - activity-content-development-revision.qmd
    #     - 19-rubric-scoring.qmd
    #     - activity-scoring-with-rubrics.qmd
    #     - activity-chained-workflows.qmd
    #     - activity-shiny-app-development.qmd
    #     - 24-rag-models.qmd

  
  sidebar:
    collapse-level: 1
        
bibliography: references.bib
csl: american-medical-association.csl

execute:
  echo: true
  eval: true
  engine: knitr 
  
format:
  html:
    theme: spacelab
    toc: true
    toc-depth: 4
    number-depth: 4
    css: style.css
    code-fold: show
    code-tools: true
    code-copy: true
    code-link: true
    link-citations: true
    citation-hover: true
    link-external-newwindow: true
    
website:
  site-url: https://runyoncr.github.io/AIMECON_R_WORKSHOP
  repo-url: https://github.com/runyoncr/AIMECON_R_WORKSHOP