project:
  type: book
  output-dir: _book

book:
  title: "Integrating Generative AI into R Workflows: From APIs to Shiny Apps"
  author: "Christopher Runyon"
  date: today
  
  page-footer:
    left: |
      This workshop was developed by Christopher Runyon.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  
  cover-image: workshopcover.png
  favicon: workshopcover.png
  
  chapters:
    # - index.qmd
    
    - part: 00-preparation.qmd
      chapters:
        - 00a-R-setup.qmd
        - 00b-R-packages.qmd
    
    - part: 01-gen-ai-fundamentals.qmd  
      chapters:
        - 01a-gen-ai-basics.qmd
        - 01b-gen-ai-learning.qmd
    
    - part: 02-prompt-engineering.qmd
      chapters: 
        - 02a-general-prompt-information.qmd
        - 02b-prompt-formulas.qmd
        - 02c-chained-workflows.qmd
    
    - part: 03-api-implementation.qmd
      chapters: 
        - 03a-api-keys.qmd
        - 03b-prompting-models.qmd
    
    - part: 04-ellmer.qmd
      chapters: 
        - 04a-conversations-via-api.qmd
        - 04b-rag-models.qmd
    
    - part: 05-shiny-integration.qmd
      chapters: 
        - 05a-shiny.qmd
        - 05b-vibe-coding.qmd
        
    - 06-reference-materials.qmd
    # - part: 06-reference-materials.qmd
    #   chapters: 
    #     - 06a-basic-refs.qmd
    #     - 06b-ref-guides.qmd
    #     - 06c-shiny-resources.qmd
    #     - 06d-legal-info.qmd

execute:
  echo: true  # Show code by default in all chapters
  
format:
  html:
    theme: spacelab
    toc: false
    css: style.css
    code-fold: show          # Participants can show/hide code
    code-tools: true         # Download code button
    code-copy: true          # Copy code button
    code-link: true
    
website:
  site-url: https://runyoncr.github.io/AIMECON_R_WORKSHOP
  repo-url: https://github.com/runyoncr/AIMECON_R_WORKSHOP