project:
  type: book
  output-dir: _book

book:
  title: "Integrating Generative AI into R Workflows: From APIs to Shiny Apps"
  author: "Christopher Runyon"
  date: last-modified
  
  page-footer:
    left: |
      This workshop was developed by Christopher Runyon.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  
  cover-image: SimpleBookCover_Image.png
  favicon: therefore.png
  
  
  chapters:
    - index.qmd
    
    - part: "Setup"
      chapters: 
        - 01-R-setup.qmd
        - 02-R-packages.qmd
        - 03-test-connect.qmd
        - 04-api-implementation.qmd
        - 05-api-keys.qmd
         
    - part: "Generative AI Models"
      chapters: 
        - 06-gen-ai-fundamentals.qmd
        - 07-gen-ai-basics.qmd
        - 08-gen-ai-parameters.qmd
        - activity-parameter-testing.qmd
         
    - part: "Conversational Interactions"
      chapters: 
        - 10-integration.qmd
        - 11-conversations-via-api.qmd
        - activity-content-development-revision.qmd

    - part: "Transactional Interactions"
      chapters: 
        - 13-single-interactions-via-api.qmd
        - 14-prompt-engineering.qmd
        - 15-prompt-formulas.qmd
        - activity-prompt-engineering.qmd
        - 17-mitigating-variability.qmd
        - 18-batch-processing.qmd
        - 19-rubric-scoring.qmd
        - activity-scoring-with-rubrics.qmd
        - 21-chained-workflows.qmd
        - activity-chained-workflows.qmd
        - 23-calling-other-llms.qmd
        - 24-rag-models.qmd

    - part: "Vibe Coding with Shiny"
      chapters: 
        - 25-shiny.qmd
        - 26-vibe-coding.qmd
        - 27-shiny-integration.qmd
        - activity-shiny-app-development.qmd
        - 29-saving-shiny-data.qmd
        
    - part: "Resources"
      chapters: 
        - 30-reference-materials.qmd
        - 31-acknowledgements.qmd
        - 32-references.qmd
  
  sidebar:
    collapse-level: 1
        
bibliography: references.bib
csl: american-medical-association.csl

execute:
  echo: true
  eval: true
  engine: knitr 
  
format:
  html:
    theme: spacelab
    toc: false
    toc-depth: 4
    number-depth: 4
    css: style.css
    code-fold: show
    code-tools: true
    code-copy: true
    code-link: true
    link-citations: true
    citation-hover: true
    link-external-newwindow: true
    
website:
  site-url: https://runyoncr.github.io/AIMECON_R_WORKSHOP
  repo-url: https://github.com/runyoncr/AIMECON_R_WORKSHOP