project:
  type: book
  output-dir: _book

book:
  title: "AIMECON R Workshop"
  author: "Christopher Runyon"
  date: today
  
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd

format:
  html:
    theme: cosmo
    toc: true
    css: style.css

website:
  site-url: https://runyoncr.github.io/AIMECON_R_WORKSHOP
  repo-url: https://github.com/runyoncr/AIMECON_R_WORKSHOP