project:
  type: book
  output-dir: _book

book:
  title: "Integrating Generative AI into R Workflows: From APIs to Shiny Apps"
  author: "Christopher Runyon"
  date: last-modified
  
  page-footer:
    left: |
      This workshop was developed by Christopher Runyon.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  
  cover-image: SimpleBookCover_Image.png
  favicon: therefore.png
  
  chapters:
    - index.qmd
    
    - part: 00-preparation.qmd
      chapters:
        - 00a-R-setup.qmd
        - 00b-R-packages.qmd
        - 00c-test-connect.qmd
        - 00d-LLM-R-packages.qmd
    
    - part: 03-api-implementation.qmd
      chapters: 
        - 03a-api-keys.qmd
        - 03b-prompting-models.qmd
    
    - part: 01-gen-ai-fundamentals.qmd  
      chapters:
        - 01a-gen-ai-basics.qmd
        - 01b-gen-ai-parameters.qmd
        
    - activity-parameter-testing.qmd
    
    - part: 02-prompt-engineering.qmd
      chapters: 
        - 02a-general-prompt-information.qmd
        - 02b-prompt-formulas.qmd
        - 02c-chained-workflows.qmd
    
    - activity-prompt-engineering.qmd
    
    - part: 04-integration.qmd
      chapters:
        - 04a-single-interactions-via-api.qmd
        - 04b-conversations-via-api.qmd
        - 04c-rag-models.qmd
        
    - activity-content-development-revision.qmd
    
    - activity-scoring-with-rubrics.qmd
    
    - part: 05-shiny-integration.qmd
      chapters: 
        - 05a-shiny.qmd
        - 05b-vibe-coding.qmd
        
    - activity-shiny-app-development.qmd
        
    - 06-references.qmd
    
    - 07-reference-materials.qmd
    # - part: 06-reference-materials.qmd
    #   chapters: 
    #     - 07a-basic-refs.qmd
    #     - 07b-ref-guides.qmd
    #     - 07c-shiny-resources.qmd
    #     - 07d-legal-info.qmd
    
    - 08-acknowledgements.qmd

bibliography: references.bib
csl: american-medical-association.csl

execute:
  echo: true
  eval: true
  engine: knitr 
  
format:
  html:
    theme: spacelab
    toc: false
    toc-depth: 3
    css: style.css
    code-fold: show
    code-tools: true
    code-copy: true
    code-link: true
    link-citations: true
    citation-hover: true
    
website:
  site-url: https://runyoncr.github.io/AIMECON_R_WORKSHOP
  repo-url: https://github.com/runyoncr/AIMECON_R_WORKSHOP