project:
  type: book
  output-dir: _book

book:
  title: "Integrating Generative AI into R Workflows: From APIs to Shiny Apps"
  author: "Christopher Runyon"
  date: today
  
  page-footer:
    left: |
      This workshop was developed by Christopher Runyon.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  
  # cover-image: cover.jpg
  # favicon: cover.jpg
  
  chapters:
    - index.qmd
    - 00-preparation.qmd
    
    - part: 01-gen-ai-fundamentals.qmd  
      chapters:
        - 01a-gen-ai-basics.qmd
        - 01b-gen-ai-learning.qmd
    
    - 02-prompt-engineering.qmd
    - 03-api-implementation.qmd
    - 04-ellmer.qmd
    - 05-shiny-integration.qmd

format:
  html:
    theme: spacelab
    toc: true
    css: style.css
    code-fold: true          # Participants can show/hide code
    code-tools: true         # Download code button
    code-copy: true          # Copy code button
    code-link: true
    
website:
  site-url: https://runyoncr.github.io/AIMECON_R_WORKSHOP
  repo-url: https://github.com/runyoncr/AIMECON_R_WORKSHOP